name: Java CI with Mavens

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        overwrite-settings: 'false'
    - name: Build with Maven
      run: mvn clean install
    - name: Send email
      uses: dawidd6/action-send-mail@v3.6.0
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: Harshit Awasthi
          password: kanpur123#
          subject: Message from github actions.
          to: rkawasthyujvnl@gmail.com
          from: harshit
          secure: true
          body: workflow for ${{github.repository}} completed successfully!
