name: Java CI with Maven

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        overwrite-settings: 'false'
    - name: Build with Maven
      run: mvn clean install
    - name: Notify Me on Success
   
      uses: adelynx/github-actions-nodemailer@main
      with:  
    # Required mail server address:              
       host: 'smtp.office365.com'
    # Required mail server port:
       port: 587
    # Required mail server username:
       username: harsit.awasthi@celebaltech.com
    # Required mail server password:
       password: Kanpur123
    # Required mail server from:
       from: harshit
    # Required mail server to:
       to: ayush.sinha@celebaltech.com
    # Required mail subject:
       subject: 'Github Actions job result'
    # Optional plain text body:
       body: 'Build job of ${{github.repository}} completed successfully!'
    # Or HTML body
   
   
