name: Java CI with Maven

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        overwrite-settings: 'false'
    - name: Build with Maven
      run: mvn clean install
    - name: Send some mail
      uses: wadeww/send-email-action@master
      with:
       server_address: smtp.office365.com
       port: 587
       username: harshit.awasthi@celebaltech.com
       password: Kanpur123#
       subject: Workflow finished
       body: Job completed ${{job.status}}
       to: ayush.sinha@celebaltech.com
       from: harshit
